# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/energy_storage',
                'doc_host': 'https://markkvdb.github.io',
                'git_url': 'https://github.com/markkvdb/energy_storage',
                'lib_path': 'src/energy_storage'},
  'syms': { 'energy_storage.data': { 'energy_storage.data.get_production': ('data.html#get_production', 'energy_storage/data.py'),
                                     'energy_storage.data.get_spot_price': ('data.html#get_spot_price', 'energy_storage/data.py')},
            'energy_storage.optimal_dispatch': { 'energy_storage.optimal_dispatch.redistribute_daily_production': ( 'optimal_dispatch.html#redistribute_daily_production',
                                                                                                                    'energy_storage/optimal_dispatch.py')}}}
